Adding MACRO ENABLE_ENHANCED_ERROR_CODE to enalbe/disable the enhanced
rdkcentral/rdk-halif-test-deepsleep_manager pull request #6
Opened 2024-05-09 12:33 UTC by Sumip98

2024-05-10 09:37 UTC, thanushreevani commented on src/test_l1_deepSleepMgr.c
> +    #ifdef ENABLE_ENHANCED_ERROR_CODE
Add the flag after initializing variables

2024-05-10 09:37 UTC, thanushreevani commented on src/test_l1_deepSleepMgr.c
> +    #ifdef ENABLE_ENHANCED_ERROR_CODE
This case doesnt come under enhanced error code, its wrong error code. Because the scenario is handled but returning wrong value.

2024-05-10 09:37 UTC, thanushreevani commented on src/test_l1_deepSleepMgr.c
>      UT_ASSERT_EQUAL_FATAL(result, DEEPSLEEPMGR_INVALID_ARGUMENT);
This case doesnt come under enhanced error code its wrong error code. Because the scenario is handled but returning wrong value.

2024-05-13 06:14 UTC, thanushreevani commented on src/test_l1_deepSleepMgr.c
>      UT_ASSERT_EQUAL_FATAL(result, DEEPSLEEPMGR_NOT_INITIALIZED);
For  the enhance error codes NOT_INITIALISED or NOT_TERMINATED, most of the cases still return a different error.  This should be handled.
Handle in whole document

2024-05-13 17:55 UTC, srinivasgtl reviewed
Two comments need to be addressed.

2024-05-21 10:50 UTC, Ulrond requested changes
https://github.com/rdkcentral/ut-core/discussions/55 -> please update to support the KVP module , so we can commit this code as a valid upgrade, that can change configuration at runtime.

2024-05-21 10:50 UTC, Ulrond commented on src/test_l1_deepSleepMgr.c
> +     result = PLAT_DS_INIT();
https://github.com/rdkcentral/ut-core/discussions/55 -> please update to support the KVP module , so we can commit this code as a valid upgrade, that can change configuration at runtime.

2024-05-23 06:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdk-halif-test-deepsleep_manager?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdk-halif-test-deepsleep_manager?pullRequest=6) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Sumip98<br/>:x: sumip98<br/><hr/>**sumip98** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdk-halif-test-deepsleep_manager?pullRequest=6) it.</sub>

2024-05-30 13:54 UTC, Ulrond approved these changes
looks good

2024-06-05 10:07 UTC, merged